monitorv2 {
  output = eDP-1
  mode = 1920x1080@60
  position = 1920x0
  scale = 1
}

# monitorv2 {
#   output = HDMI-A-1
#   mode = 1920x1080@144
#   # mode = preffered
#   position = 0x0
#   scale = 1
# }
monitor=HDMI-A-1,preferred,auto,1,mirror,eDP-1

