background {
    monitor =
    path = ~/.dotfiles/images/wallpaper.png
    color = rgb(5b676e)

    blur_passes = 2
    blur_size = 2
}

animations {
    bezier = linear, 1, 1, 0, 0
    animation = fade, 1, 1.8, linear
}

label {
    monitor =
    text = $TIME
    color = rgb(17191a)
    font_size = 100
    font_family = Noto Sans

    position = 0, 80
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 0
    inner_color = rgba(23, 25, 26, 0.1)

    check_color=rgba(29, 168, 157, 0.1)
    fail_color=rgba(168, 42, 95, 0.1)

    font_color = rgb(17191a)
    fade_on_empty = false
    rounding = 25

    position = 0, -30
}
