source = config/monitors.conf
source = config/exec.conf
source = config/binds.conf
source = config/windowrules.conf
source = config/workspaces.conf

general {
    gaps_in = 4
    gaps_out = 8

    border_size = 1
    resize_on_border = false

    col.active_border = rgb(1da89d)
    col.inactive_border = rgb(242b2e)


    allow_tearing = false
    no_focus_fallback = true

    layout = scrolling
}

dwindle {
    pseudotile = true
    preserve_split = true
}

decoration {
    rounding = 4

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

animations {
    # enabled = false
    enabled = true

# end4
    bezier = expressiveFastSpatial, 0.42, 1.67, 0.21, 0.90
    bezier = expressiveSlowSpatial, 0.39, 1.29, 0.35, 0.98
    bezier = expressiveDefaultSpatial, 0.38, 1.21, 0.22, 1.00
    bezier = emphasizedDecel, 0.05, 0.7, 0.1, 1
    bezier = emphasizedAccel, 0.3, 0, 0.8, 0.15
    bezier = standardDecel, 0, 0, 0, 1
    bezier = menu_decel, 0.1, 1, 0, 1
    bezier = menu_accel, 0.52, 0.03, 0.72, 0.08
    bezier = stall, 1, -0.1, 0.7, 0.85
    # Configs
    # windows
    animation = windowsIn, 1, 3, emphasizedDecel, popin 80%
    animation = fadeIn, 1, 3, emphasizedDecel
    animation = windowsOut, 1, 2, emphasizedDecel, popin 90%
    animation = fadeOut, 1, 2, emphasizedDecel
    animation = windowsMove, 1, 3, emphasizedDecel, slide
    animation = border, 1, 10, emphasizedDecel
    # layers
    animation = layersIn, 1, 2.5, emphasizedDecel, popin 90%
    animation = layersOut, 1, 2, menu_accel, popin 90%
    # fade
    animation = fadeLayersIn, 1, 0.5, menu_decel
    animation = fadeLayersOut, 1, 2, stall
    # workspaces
    animation = workspaces, 1, 7, menu_decel, slidevert
    ## specialWorkspace
    animation = specialWorkspaceIn, 1, 2.8, emphasizedDecel, slide
    animation = specialWorkspaceOut, 1, 1.2, emphasizedAccel, slide
    # zoom
    animation = zoomFactor, 1, 3, standardDecel
}

input {
    kb_layout = us,lt
    kb_options = grp:win_space_toggle, ctrl:nocaps
    numlock_by_default = true

    follow_mouse = 2
    sensitivity = 0.0
    accel_profile = flat

    touchpad {
        natural_scroll = true
        scroll_factor = 0.5
    }
}

device {
    name = msft0001:00-06cb:ce2d-touchpad
    sensitivity = 1
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    disable_autoreload = false
}

xwayland {
    force_zero_scaling = true
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
}

