#!/usr/bin/env bash

_initDirs() {
    mkdir -p "$HOME/.config" "$HOME/.local/bin" "$HOME/.local/share/themes" "$HOME/.local/share/icons"
}

_checkDir() {
}
export _checkDir

_link() {
    echo "==> Linking .config files"
    find $(pwd)/config/.config -maxdepth 1 -type d -not -name '.config' -exec sh -c 'ln -sfn "$1" "$HOME/.config/$(basename "$1")"' _ {} \;

    echo "==> Installing GTK theme"
    tar xzf $(pwd)/config/.local/share/themes/oomox-tzfn.tar.gz -C $HOME/.local/share/themes

    echo "==> Installing icon theme"
    tar xzf $(pwd)/config/.local/share/icons/oomox-tzfn.tar.gz -C $HOME/.local/share/icons

    echo "==> Linking $HOME configuration files"
    find $(pwd)/config -maxdepth 1 -type f -name '.*' -exec sh -c 'ln -sfn "$1" "$HOME/$(basename "$1")"' _ {} ';'

    echo "==> Linking scripts"
    find $(pwd)/scripts -maxdepth 1 -type f -not -name 'scripts' -exec sh -c 'ln -sfn "$1" "$HOME/.local/bin/$(basename "$1")"' _ {} ';'
}

_initDirs
_link
