#!/usr/bin/env bash

PACKAGES=(hyprland sddm xdg-desktop-portal-hyprland)

DEV_PACKAGES=()

install_packages() {
    sudo pacman -S --needed --noconfirm base-devel
    git clone https://aur.archlinux.org/yay-bin.git ~/yay
    pushd ~/yay-bin
    makepkg -si
    popd

    yay -S --needed --noconfirm "${WM_PACKAGES[@]}"
}

link() {
    echo "==> Linking .config files"
    find $(pwd)/env/.config -maxdepth 1 -type d -not -name '.config' -exec sh -c 'ln -sfn "$1" "$HOME/.config/$(basename "$1")"' _ {} \;

    echo "==> Linking theme"
    ln -sfn $HOME/.dotfiles/env/.local/share/themes/oomox-rxze49/ $HOME/.local/share/themes

    echo "==> Linking icon theme"
    ln -sfn $HOME/.dotfiles/env/.local/share/icons/oomox-rxze49/ $HOME/.local/share/icons

    echo "==> Linking $HOME configuration files"
    find $(pwd)/env -maxdepth 1 -name '.*' -exec sh -c 'ln -sfn "$1" "$HOME/$(basename "$1")"' _ {} ';'

    echo "==> Linking scripts"
    find $(pwd)/scripts -maxdepth 1 -not -name 'scripts' -exec sh -c 'ln -sfn "$1" "$HOME/.local/bin/$(basename "$1")"' _ {} ';'
}

link
