#!/usr/bin/env bash

commit_msg="${1:-lil buhb forgor commit msg hehehehaw}"

if ! git diff --quiet env/nvim || ! git diff --cached --quiet env/nvim; then
    pushd env/.config/nvim
    git add .
    git commit -m "$commit_msg"
    git push
    popd
fi

if ! git diff --quiet . || ! git diff --cached --quiet .; then
    git add .
    git commit -m "$commit_msg"
    git push
fi
