#!/usr/bin/env bash

git diff --quiet env/nvim
nvim_changed=$?

if ! git diff --quiet . || ! git diff --cached --quiet .; then
    git add .
    git commit -m "$1"
    git push
fi

if ! [ $nvim_changed -eq 1]; then
    git subtree push --prefix env/nvim git@github.com:martynasmuizys/nvim-rc.git main --squash
fi
