#!/usr/bin/env bash

commit_msg="${1:-lil buhb forgor commit msg hehehehaw}"

if ! git diff --quiet config/.config/nvim || ! git diff --cached --quiet config/.config/nvim; then
    pushd config/.config/nvim
    git add .
    git commit -m "$commit_msg"
    git push
    popd
fi

if ! git diff --quiet . || ! git diff --cached --quiet .; then
    git add .
    git commit -m "$commit_msg"
    git push
fi
