#!/usr/bin/env bash

nvim_changed=$(git diff -- quiet env/nvim)

if ! git diff --quiet . || ! git diff --cached --quiet .; then
    git add .
    git commit -m "$1"
    git push
fi

if ! $nvim_changed; then
    git subtree push --prefix env/nvim git@github.com:martynasmuizys/nvim-rc.git main --squash
fi
