[colors.primary]
foreground = "#d6d9e0"
background = "#17191a"
dim_foreground = "#d6cfcf"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#d6d9e0"
cursor = "#574c59"

[colors.vi_mode_cursor]
text = "#d6d9e0"
cursor = "#574c59"

[colors.search.matches]
foreground = "#d6d9e0"
background = "#462c47"

[colors.search.focused_match]
foreground = "#201822"
background = "#f84a12"

[colors.hints.start]
foreground = "#d6d9e0"
background = "#202426"

[colors.hints.end]
foreground = "#cfcfd6"
background = "#202426"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#d6d9e0"
background = "#202426"

[colors.selection]
text = "#d6d9e0"
background = "#3e3640"

[colors.normal]
black = "#17191a"
red = "#f84a12"
green = "#36994e"
yellow = "#ffaf0a"
blue = "#558ba6"
magenta = "#a82a5f"
cyan = "#1da89d"
white = "#d6d9e0"

[colors.bright]
black = "#5b676e"
red = "#fa835c"
green = "#5ecc79"
yellow = "#ffb724"
blue = "#79b9d9"
magenta = "#db4282"
cyan = "#30dbcd"
white = "#ffffff"

[colors.dim]
black = "#121414"
red = "#ab5a3f"
green = "#324d38"
yellow = "#b38b3d"
blue = "#485459"
magenta = "#5c3244"
cyan = "#2b5c58"
white = "#949494"
