exec-once = uwsm-app -- nm-applet

# i mean why would i want to persist after boot? i barely use it anyways
exec-once = cliphist clear
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
